make response local in fetchData fun
r426/CurrencyExchange pull request #10
Opened 2020-07-23 18:36 UTC by r426

2020-07-26 05:49 UTC, RokasMak requested changes

2020-07-26 05:49 UTC, RokasMak commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
> +        var response: retrofit2.Response<Currency>?
Remove this line

2020-07-26 05:49 UTC, RokasMak commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
>                  response = ServiceFactory.createRetrofitService(
write 'val' before response

2020-07-26 05:49 UTC, RokasMak commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
> +                if (response!!.body() != null) {
remove nullable types

2020-07-27 10:21 UTC, r426 commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
> +        var response: retrofit2.Response<Currency>?
removed

2020-07-27 10:21 UTC, r426 commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
>                  response = ServiceFactory.createRetrofitService(
added

2020-07-27 10:21 UTC, r426 commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
> +                if (response!!.body() != null) {
removed

2020-07-27 13:44 UTC, RokasMak requested changes

2020-07-27 13:44 UTC, RokasMak commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
> +                }
Replace this with: 
`           response.body()?.let{body ->
                    calculateValues(body)
                    makeInfoMessage(body)
                }
                if (response.body() == null) {
                    _error.postValue(Unit)
                }`

2020-07-27 13:44 UTC, RokasMak commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
> +    private fun makeInfoMessage(responseBody: Currency?) {
rename responseBody to currency. Remove nullable type

2020-07-27 13:44 UTC, RokasMak commented on app/src/main/java/com/ryeslim/currencyexchange/MainViewModel.kt
> +    private fun calculateValues(responseBody: Currency?) {
rename responseBody to currency. Remove nullable type

2020-07-28 06:16 UTC, RokasMak approved these changes

2020-07-28 06:35 UTC, merged